### ISSUE TITLE
Git checkout can not clean the repo at 2nd build

### ISSUE THREAD

**Issue by brookman** [game-ci/unity-actions#142]
**Bug description**

We are using self hosted Github Action Runners because the ones from Github are not available on Enterprise.
This means the build machine might be re-used and still contains all the files from the last build.

After building once the project directory contains files and directories which belong to the root user. At the checkout step of the next build the actions/checkout@v2 tries to clean the directory (with git clean -ffdx) but fails because it can't delete those files belonging to root.

I assume this is because the Docker build containers run as root and write to mounted volumes with that user.

**How to reproduce**

- Register a self hosted runner (for example an Ubuntu VM).
- Run a simple build.
- The file system looks something like this:
![image](https://user-images.githubusercontent.com/1568303/161843440-c15d56ec-fa1f-40ac-80d7-ac4d41792dad.png)
- Run the build again
- Output:
```
Cleaning the repository
  /usr/bin/git clean -ffdx
warning: failed to remove Assets/Editor/Editor/UnityBuilderAction.meta: Permission denied
...
Warning: Unable to clean or reset the repository. The repository will be recreated instead.
Deleting the contents of '/home/user/workspace/myProject/actions-runner/_work/myRepo/myRepo'
Error: Command failed: rm -rf "/home/user/workspace/myProject/actions-runner/_work/myRepo/myRepo/Assets"
```

**Expected behavior**

If possible the build containers should not write to the host file system as root.

**Additional details**

I have tried to disable cleaning the repo but this does not work reliably:
```
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: false
```

**Comment by webbertakken** [comment]
Thank you for reporting this bug @brookman.

I have seen issues about this before, either in this repo, or in unity-test-runner or in unity-builder and also on discord (searching there might help quite a bit).

> I assume this is because the Docker build containers run as root and write to mounted volumes with that user.

This seems to often be the first assumption, however it doesn't explain why it is causing problems for only very few teams.
That said, since most of the teams that this would happen to are probably enterprise scale, they might fix their issues in-house and not share the solution here.

That's not to say we don't want to fix the issue. We've gone down the road of trying to make the images non-root before and decided:
- using root in a docker image that's used in CI only isn't bad practice at all,
- when we tried either way, it turned out not to be a viable solution, yet brought a lot of complexity with it and
- the root cause is actually in the GitHub self-hosted runner not handling files in docker mounts correctly.

For more information see this PR https://github.com/game-ci/docker/pull/106 and the discussions on discord.

A few things I could think of:

- `chown`ing or deleting the files at the end of the previous run as a quick fix
- changing runner setup or asking GitHub Actions for support, especially also check for settings that might affect this behaviour
- see what others came up with on Discord

Please don't hesitate to post your findings in this issue, so it's transparent for everyone and the community might be able to pitch in as well.

**Comment by mastef** [comment]
Just a note from our team: We do chown before and after each builder run in
a separate step

**Comment by webbertakken** [comment]
I'm assuming that worked as Mastef confirmed this as a working solution before as well.
