### ISSUE TITLE
Add support for blender files (.blend) or throw an error.

### ISSUE THREAD

**Issue by schaubli** [game-ci/unity-actions#146]
**Context**

Unity uses the installed blender executable to automatically convert .blend files in the project to .fbx files. This way, you are able to keep only the blender files in the project and unity converts them for you. (Read more [here](https://docs.unity3d.com/Manual/HOWTO-ImportObjectsFrom3DApps.html#Blender))
Unfortunately, this is not supported by the action and 3D models from blender files are not shown in the executable, but also no error is shown during running the action.

**Suggested solution**

To fix this, the unity action could either:

1. Support .blend files and convert them on build.
2. Throw an error if a .blend file is used, as it cannot be converted automatically.

**Considered alternatives**

My workaround for now was to manually export the blender file into an fbx and reapplied materials which is then correctly processed. This however, clutters the project and also requires multiple manual steps when changing anything in the model.

**Comment by webbertakken** [comment]
Excellent suggestion.

We should probably implement both.

For option 1:
- it would require blender itself to be installed on top of the image. 
- We have already decided that we do not want to add this to our docker repository because next to blender there are at least 5 other packages people would want installed (see for example the other file formats unity supports), and publishing all different combinations for all versions for all target platforms is not feasible.
- That said, we have two solutions to this challenge:
  - For smaller teams and projects we plan to implement a plugin system, where in this example a blender build plugin would install blender on runtime on every workflow run.
  - For larger teams and projects we always recommend publishing your own image based on our maintained images, and put blender on top. Just adding blender should make your project work out of the box.

For option 2:
- Excellent idea. Any idea how to easily detect this? Should we capture the error or scan the project beforehand?

**Comment by schaubli** [comment]
That plugin system sounds great but I guess it will require a whole lot of changes. I guess as a first step, it would be easier to have instructions available on how to use your own docker image and install blender there.

The error message you get when blender isn't installed is something like: `Prefab instance problem: <Prefab Instance Name>. <X> instances are missing the same Prefab`. Unfortunately this error message isn't precise and could probably also be cause by other issues than blender files, but it might be a starting point. 
IMO scanning the project for .blender files is less accurate, as you could have blender files but not use them in your scenes which should not cause an issue.

**Comment by webbertakken** [comment]
Indeed, the plugin system is kind of a long term thing.

We'd welcome any contributions to the docs on how to customise your own image. We're dependent on contributions from the community for non-standard use cases as core contributors only work on the project in their free time currently.

**Comment by webbertakken** [comment]
Added this to the [Roadmap to v3.0.0](https://github.com/orgs/game-ci/projects/4/views/1).
